### ISSUE TITLE
program crashes when calibrating single point with no target

### ISSUE THREAD

**Issue by OmerZ7** [Chameleon-Vision/chameleon-vision#12]
when pressing calibrate in single point mode, when there are no targets, list<number>points will have nulls in it and crash the next time a target is found

fixed in crosshair branch
waiting for code review

fixed in collect2dtargetpipe and in draw2dcrosshairpipe

**Comment by OmerZ7** [comment]
Current status: fixed, waiting for code review and cleanup by arganight

Java fix: 054e6dd
Java fix reverted: 7bec1bf
UI fix: d18954f

Also related
UI fix for clear single point: 2040620

**Comment by oriagranat9** [comment]
ui cleanup in aeb08442dd715dc925683669cb50573f64e9b35a
