### ISSUE TITLE
Crosshair does not move to center when image is rotated

### ISSUE THREAD

**Issue by Bankst** [Chameleon-Vision/chameleon-vision#16]
When rotating the image to 90 CW or 90 CCW, the crosshair does not move to the new center

**Comment by OmerZ7** [comment]
Commits:
Added recenter when sending empty list in points 20406202701e5655385352bd7406e29bcbd54672
Sending empty list when rotating and set CaptureStaticProperties when rotating 339d6dc478e6f3e374f551307923b95317cac191
