### ISSUE TITLE
StreamDivisor not updating on program start

### ISSUE THREAD

**Issue by Bankst** [Chameleon-Vision/chameleon-vision#19]
Problems with StreamDivisor
1. Doesnt load on startup
2. Doesnt load on res change
3. Doesnt load on pipeline change

check if works with dual cameras

**Comment by OmerZ7** [comment]
0a051a88a3d0e04543ccb0b0ffec2a7046bca46c

**Comment by OmerZ7** [comment]
fix for stream divisor when rotating by 90 0a051a88a3d0e04543ccb0b0ffec2a7046bca46c
