### ISSUE TITLE
PS3 Eye Doesn't work in 2.1/2.1.1

### ISSUE THREAD

**Issue by Tekunalogy** [Chameleon-Vision/chameleon-vision#44]
- Used WinSCP to transfer 2.1 and 2.1.1 jar files to rpi in the /home/pi directory.
- Plugged in PS3 Eye usb camera into the RPi. ran "sudo java -jar [chameleon vision jar file name].jar"
- All JAR Files were verified to be not corrupted. They all run, but only version 2.0 works. The following is the output from releases 2.1/2.1.1 when running the above setup.

> pi@team3647pi:~ $ sudo java -jar chameleon-vision-2.1-RELEASE.jar
Starting Chameleon Vision on platform Linux Raspbian
Settings folder: /boot/chameleon-vision/settings
No valid network interfaces found! Staying unmanaged.
VIDEOIO ERROR: V4L2: Unable to capture video memory.VIDEOIO ERROR: V4L: can't open camera by index 10
/dev/video10 does not support memory mapping
VIDEOIO ERROR: V4L2: Unable to capture video memory.VIDEOIO ERROR: V4L: can't open camera by index 11
/dev/video11 does not support memory mapping
VIDEOIO ERROR: V4L2: Unable to capture video memory.VIDEOIO ERROR: V4L: can't open camera by index 12
/dev/video12 does not support memory mapping
setting perms on /boot/chameleon-vision/settings/cameras/USB_Camera-B4.09.24.1/pipelines
setting perms on /boot/chameleon-vision/settings/cameras/USB_Camera-B4.09.24.1/pipelines/New_Pipeline.json
setting perms on /boot/chameleon-vision/settings/cameras/USB_Camera-B4.09.24.1/pipelines
setting perms on /boot/chameleon-vision/settings/cameras/USB_Camera-B4.09.24.1/pipelines/New_Pipeline.json
Failed to load camera calibration: /boot/chameleon-vision/settings/cameras/USB_Camera-B4.09.24.1/drivermode.json
Exception in thread "main" java.lang.NullPointerException
        at com.chameleonvision.vision.camera.USBCameraCapture.<init>(USBCameraCapture.java:29)
        at com.chameleonvision.vision.VisionManager.initializeProcesses(VisionManager.java:86)
        at com.chameleonvision.Main.main(Main.java:174)
NT Connection has failed!

**Comment by oriagranat9** [comment]
known bug and has been fixed
