### ISSUE TITLE
A couple of errors

### ISSUE THREAD

**Issue by ramhawks** [Chameleon-Vision/chameleon-vision#57]
Hi!  

Im trying to use chameleon vision with a raspi 3, but i keep getting errors.  On the pi when running `sudo java -jar chameleon-vision.jar` It get stuck on "NT Connection has failed! Will retry in background."

On the pc, I get a couple of errors too.  the first:
![aasasasasass](https://user-images.githubusercontent.com/22802387/73496942-4540be80-437f-11ea-9d5c-473065f06250.png)
And the second, once I close down vscode, shuffleboard, and the driverstation:
![asasasdsdsddfdfdfdfdfdf](https://user-images.githubusercontent.com/22802387/73497025-70c3a900-437f-11ea-9363-125ed3e3dbf6.png)

How can I fix these?

**Comment by ramhawks** [comment]
update:   installed the vc++ exe that it was trying to get but i get the same error

**Comment by oriagranat9** [comment]
this seem to be a problem with your pc and not chameleon try restarting and see if that helps

**Comment by ramhawks** [comment]
i restarted but still no bueno.

**Comment by oriagranat9** [comment]
Please use java 12 and try again

**Comment by Bankst** [comment]
No update for almost 4 months, considering solved. Re-open this issue if you still have problems.
