### ISSUE TITLE
Add NetworkTables entry for latency

### ISSUE THREAD

**Issue by prateekma** [Chameleon-Vision/chameleon-vision#6]
A latency entry would be more useful than a timestamp entry. Although this latency value wouldn't compensate for network lag, the documentation could provide users with a "known value" (for example, Limelight docs say 11 milliseconds).

**Comment by Bankst** [comment]
Fixed in 0446d3e, needs testing. [Artifact here](https://371-222512581-gh.circle-artifacts.com/0/root/project/chameleon-server/target/chameleon-vision-2.0.1-BETA.jar)
