### ISSUE TITLE
Multiple Cameras with Chameleon Vision

### ISSUE THREAD

**Issue by Warrior-Robotics-Salamanca** [Chameleon-Vision/chameleon-vision#66]
Our team has been using Chameleon vision for a few weeks now and we wanted to add a few cameras onto the raspberry pi. With 3 cameras on the system, the interface only displays 2 of the cameras, seemingly chosen randomly. Our team would like to use the raspberry pi to stream all 3 cameras, even though 1 will have a functional pipeline. Another issue when using multiple cameras is that setting the driverMode entry of the database will crash all cameras connected.

**Comment by oriagranat9** [comment]
having so many cameras connected may be to much for the pi USB controller bandwidth and may cause unexpected crashes or incorrect behavior there is nothing we can do about that.
for more details about that issue take a look in our discord it was already answered there
