### ISSUE TITLE
Unknown Platform! OS: Mac OS X error

### ISSUE THREAD

**Issue by tanayshah44** [Chameleon-Vision/chameleon-vision#98]
When I run the java -jar chameleon-vision-X.X-RELEASE.jar --unmanage-network command in terminal I get this error:
Unknown Platform. OS: Mac OS X, Architecture: x86_64
Unknown Platform! OS: Mac OS X, Architecture: x86_64Tanays-MacBook-Air:chameleon

Can you please help me fix this issue

**Comment by Bankst** [comment]
As of the current 2.x.x release, Mac OS is "unsupported". It will, however, still likely run fine.
You can bypass this check by cloning the master branch and building yourself. The corresponding check is in `util\Platform.java`.

This is already fixed in the upcoming 3.0 release.
